# Generated by Django 5.2.6 on 2026-07-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicerecord",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
